# Generated by Django 6.0.2 on 2026-03-04 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_school_department_school"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("exam", "Examination Period"),
                            ("registration", "Registration Period"),
                            ("classes_start", "Classes Start"),
                            ("classes_end", "Classes End"),
                            ("break", "Break"),
                            ("event", "Event"),
                            ("deadline", "Deadline"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_university_wide",
                    models.BooleanField(
                        default=True, help_text="Applies to the entire university"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="If not university-wide, specific department",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_events",
                        to="academics.department",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_events",
                        to="academics.semester",
                    ),
                ),
            ],
            options={
                "db_table": "academic_events",
                "ordering": ["start_date"],
            },
        ),
    ]
