# Generated by Django 6.0.2 on 2026-03-04 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_academicevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="credit_limit",
            field=models.IntegerField(
                default=24, help_text="Max credits a student can take per semester"
            ),
        ),
        migrations.CreateModel(
            name="CoursePrerequisite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("prerequisite", "Prerequisite"),
                            ("corequisite", "Co-requisite"),
                        ],
                        default="prerequisite",
                        max_length=20,
                    ),
                ),
                (
                    "min_grade",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Minimum grade required (e.g. 'C'), blank = just pass",
                        max_length=5,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course that has the prerequisite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="academics.course",
                    ),
                ),
                (
                    "required_course",
                    models.ForeignKey(
                        help_text="The course that must be completed first",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="is_prerequisite_for",
                        to="academics.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_prerequisites",
                "unique_together": {("course", "required_course")},
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "grade_letter",
                    models.CharField(
                        choices=[
                            ("O", "Outstanding (10)"),
                            ("A+", "Excellent (9)"),
                            ("A", "Very Good (8)"),
                            ("B+", "Good (7)"),
                            ("B", "Above Average (6)"),
                            ("C", "Average (5)"),
                            ("D", "Below Average (4)"),
                            ("F", "Fail (0)"),
                            ("W", "Withdrawn"),
                            ("I", "Incomplete"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "credits_earned",
                    models.IntegerField(
                        default=0, help_text="Credits earned (0 if failed/withdrawn)"
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="academics.courseoffering",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "grades",
                "ordering": ["-course_offering__semester__start_date"],
                "unique_together": {("student", "course_offering")},
            },
        ),
    ]
