# Generated by Django 6.0.3 on 2026-03-07 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_studenttask"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice (Multiple Correct)"),
                            ("single", "Single Choice"),
                            ("programming", "Programming"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="For MCQ/Single: array of {id, text} objects",
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        help_text="For MCQ: array of option ids, for Single: single option id, for Programming: expected output"
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        blank=True,
                        help_text="For Programming: array of {input, expected_output}",
                        null=True,
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True,
                        help_text="Optional starter code for programming questions",
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Programming language (python, java, c++, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("points", models.IntegerField(default=1)),
                (
                    "time_limit_minutes",
                    models.IntegerField(
                        default=30, help_text="Time limit in minutes for solving"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Date when question should be available"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True,
                        help_text="Specific start time (optional)",
                        null=True,
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, help_text="Specific end time (optional)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_offering",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_questions",
                        to="academics.courseoffering",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_questions",
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuestionAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch",
                    models.CharField(
                        blank=True,
                        help_text="Student's batch when assigned",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("started", "Started"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_taken_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken in seconds from start to submit",
                        null=True,
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True,
                        help_text="If false, submission was flagged as cheating",
                    ),
                ),
                (
                    "invalid_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academics.dailyquestion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_question_assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("question", "student")},
            },
        ),
        migrations.CreateModel(
            name="DailyQuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "selected_options",
                    models.JSONField(
                        blank=True,
                        help_text="For MCQ/Single: array of selected option ids",
                        null=True,
                    ),
                ),
                (
                    "code_answer",
                    models.TextField(
                        blank=True,
                        help_text="For Programming: student's code submission",
                        null=True,
                    ),
                ),
                (
                    "output_result",
                    models.TextField(
                        blank=True,
                        help_text="Actual output from running code",
                        null=True,
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("is_manually_verified", models.BooleanField(default=False)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="academics.dailyquestionassignment",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_question_responses",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentDailyQuestionPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_assigned", models.IntegerField(default=0)),
                ("total_submitted", models.IntegerField(default=0)),
                ("total_correct", models.IntegerField(default=0)),
                ("total_points_earned", models.IntegerField(default=0)),
                ("total_time_seconds", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Consecutive days of correct submissions"
                    ),
                ),
                ("longest_streak", models.IntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_performance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_dq_performance",
                "ordering": ["-date"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
