# Generated by Django 6.0.2 on 2026-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_contentcomment_contentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
