# Generated by Django 6.0.2 on 2026-03-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_studentprofile_batch_studentprofile_division_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("faculty", "Faculty"),
                    ("dean", "Dean"),
                    ("head", "Faculty Head"),
                    ("student", "Student"),
                ],
                max_length=20,
            ),
        ),
    ]
