# Generated by Django 6.0.2 on 2026-03-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_dean_head_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="roll_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
