# Generated by Django 6.0.2 on 2026-03-06 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_deleted_at_user_is_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="system",
                        help_text="light, dark, or system",
                        max_length=20,
                    ),
                ),
                (
                    "calendar_view",
                    models.CharField(
                        default="week", help_text="month, week, or day", max_length=20
                    ),
                ),
                ("compact_sidebar", models.BooleanField(default=False)),
                ("language", models.CharField(default="en", max_length=10)),
                ("timezone", models.CharField(default="asia_kolkata", max_length=50)),
                ("date_format", models.CharField(default="dd_mm_yyyy", max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
    ]
