# Generated by Django 6.0.2 on 2026-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="late_penalty_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="% per day or flat marks to deduct",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="late_policy",
            field=models.CharField(
                choices=[
                    ("none", "No Penalty"),
                    ("percentage_per_day", "% Deduction Per Day"),
                    ("flat_deduction", "Flat Mark Deduction"),
                    ("no_accept", "Do Not Accept Late"),
                ],
                default="none",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="max_late_days",
            field=models.IntegerField(
                default=0, help_text="Maximum days late allowed (0 = unlimited)"
            ),
        ),
    ]
