# Generated by Django 6.0.2 on 2026-03-04 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0002_assignment_late_penalty_value_assignment_late_policy_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_final",
            field=models.BooleanField(
                default=True, help_text="Is this the final submission to be graded?"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="GradingRubric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_rubrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "grading_rubrics",
            },
        ),
        migrations.CreateModel(
            name="AssignmentGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="assignment_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="group",
                        to="assignments.submission",
                    ),
                ),
            ],
            options={
                "db_table": "assignment_groups",
                "ordering": ["name"],
                "unique_together": {("assignment", "name")},
            },
        ),
        migrations.CreateModel(
            name="RubricCriteria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("max_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="assignments.gradingrubric",
                    ),
                ),
            ],
            options={
                "db_table": "rubric_criteria",
                "ordering": ["order", "name"],
                "unique_together": {("rubric", "name")},
            },
        ),
    ]
