# Generated by Django 6.0.2 on 2026-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0003_alter_submission_unique_together_submission_is_final_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
