# Generated by Django 6.0.2 on 2026-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_webhookendpoint_webhookdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="attachments",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of attachment metadata, e.g. [{'url': '...', 'name': '...'}]",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="messages/files/"),
        ),
        migrations.AddField(
            model_name="message",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
