# Generated by Django 6.0.2 on 2026-03-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetableentry",
            name="room",
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="batch",
            field=models.CharField(
                default="", help_text="e.g. A1, B2, CS-2024", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="location",
            field=models.CharField(
                default="",
                help_text="Free-text room/lab, e.g. 'Floor 1 Room 150', 'Lab B1'",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("classroom", "Classroom"),
                    ("lab", "Laboratory"),
                    ("tutorial", "Tutorial"),
                ],
                default="classroom",
                max_length=20,
            ),
        ),
    ]
