# Generated by Django 6.0.2 on 2026-03-04 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_add_batch_subject_type_location_remove_room_fk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimetableSwapRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional message explaining the swap reason",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="Faculty who initiated the swap request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester_entry",
                    models.ForeignKey(
                        help_text="Requester's timetable slot to swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_as_requester",
                        to="timetable.timetableentry",
                    ),
                ),
                (
                    "target_entry",
                    models.ForeignKey(
                        help_text="Target faculty's timetable slot to swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_as_target",
                        to="timetable.timetableentry",
                    ),
                ),
                (
                    "target_faculty",
                    models.ForeignKey(
                        help_text="Faculty who must approve the swap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_swap_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "timetable_swap_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
