# Generated by Django 6.0.2 on 2026-03-04 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0003_timetableswaprequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_date",
                    models.DateField(
                        help_text="The date the class was supposed to occur"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("new_date", models.DateField(blank=True, null=True)),
                ("new_start_time", models.TimeField(blank=True, null=True)),
                ("new_end_time", models.TimeField(blank=True, null=True)),
                (
                    "new_location",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_cancellations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="timetable.timetableentry",
                    ),
                ),
            ],
            options={
                "db_table": "class_cancellations",
                "ordering": ["-original_date"],
                "unique_together": {("timetable_entry", "original_date")},
            },
        ),
    ]
