# Generated by Django 6.0.2 on 2026-03-04 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0004_classcancellation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classcancellation",
            name="is_makeup",
            field=models.BooleanField(
                default=False,
                help_text="Does this cancellation have a linked makeup session?",
            ),
        ),
        migrations.AddField(
            model_name="classcancellation",
            name="makeup_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="The one-off TimetableEntry created as a makeup for this class.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makeup_for_cancellation",
                to="timetable.timetableentry",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="is_oneoff",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is a one-time makeup or extra session, not a regular weekly class.",
            ),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="oneoff_date",
            field=models.DateField(
                blank=True,
                help_text="Required if is_oneoff is True. The specific date of the session.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("purpose", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="timetable.room",
                    ),
                ),
            ],
            options={
                "db_table": "room_bookings",
                "ordering": ["-date", "-start_time"],
                "unique_together": {("room", "date", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="SubstituteFaculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_substitutes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitute_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutes",
                        to="timetable.timetableentry",
                    ),
                ),
            ],
            options={
                "db_table": "substitute_faculty",
                "ordering": ["-date"],
                "unique_together": {("timetable_entry", "date")},
            },
        ),
    ]
