# Generated by Django 6.0.2 on 2026-03-06 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "institution_name",
                    models.CharField(default="NimbusU University", max_length=255),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@nimbusu.edu", max_length=254),
                ),
                ("academic_year", models.CharField(default="2024-2025", max_length=20)),
                ("enable_student_registration", models.BooleanField(default=False)),
                ("enable_file_uploads", models.BooleanField(default=True)),
                ("enable_forum_discussions", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Site Settings",
                "db_table": "site_settings",
            },
        ),
    ]
